name: Cinc performance testing

on:
  workflow_dispatch

jobs:
  macOS:
    runs-on: macos-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    timeout-minutes: 15
    env:
      CINC_CLIENT_SHA256: "c1b44b67d4cbd0c46833b5b6082ce494f4194ad91704ab7d8ba3170f5d72039f"
      CINC_CLIENT_DMG_URL: "https://ftp.osuosl.org/pub/cinc/files/stable/cinc/18.2.7/mac_os_x/12/cinc-18.2.7-1.x86_64.dmg"  # OSUOSL hosts a TLS-enabled mirror of downloads.cinc.sh
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

      - name: Cache Cinc installer
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
        id: cinc-dmg-cache
        with:
          path: /tmp/cinc.dmg
          key: ${{ runner.os }}-cinc-installer-${{ env.CINC_CLIENT_SHA256 }}

      - name: Download Cinc
        if: steps.cinc-dmg-cache.outputs.cache-hit != 'true'
        run: |
          curl -L $CINC_CLIENT_DMG_URL --output /tmp/cinc.dmg

      - name: Verify Cinc checksum
        working-directory: /tmp
        run: |
          echo "${{ env.CINC_CLIENT_SHA256 }} cinc.dmg" >> SHA256SUM
          if shasum -a 256 cinc.dmg; then
            echo "SHA256 checksum matches."
          else
            echo "SHA256 checksum failure."
            exit 1
          fi

      - name: Install Cinc
        run: |
          hdiutil mount /tmp/cinc.dmg -mountpoint /Volumes/Cinc
          sudo installer -pkg /Volumes/Cinc/cinc-*.x86_64.pkg -target /

      - name: Run Cinc
        run: |
          sudo cinc-client -z -o example

  Windows:
    runs-on: windows-2022
    if: ${{ github.actor != 'dependabot[bot]' }}
    timeout-minutes: 15
    env:
      CINC_CLIENT_SHA256: "238032b3f9fc24ee1b2c858e069b0043746218140d5fb3dd07123d632b7fb5bf"
      CINC_CLIENT_MSI_URL: "https://ftp.osuosl.org/pub/cinc/files/stable/cinc/18.2.7/windows/2012r2/cinc-18.2.7-1-x64.msi"  # OSUOSL hosts a TLS-enabled mirror of downloads.cinc.sh
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          path: chef-repo

      - name: Cache Cinc installer
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
        id: cinc-msi-cache
        with:
          path: C:\cinc.msi
          key: ${{ runner.os }}-cinc-installer-${{ env.CINC_CLIENT_SHA256 }}

      - name: Download Cinc
        if: steps.cinc-msi-cache.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri ${{ env.CINC_CLIENT_MSI_URL }} -OutFile C:\cinc.msi

      - name: Calculate Cinc checksum
        run: |
          chcp 65001 #set code page to utf-8
          echo ("DOWNLOADED_MSI=" + $(Get-FileHash c:\cinc.msi -Algorithm SHA256 | Select-Object -ExpandProperty Hash)) >> $env:GITHUB_ENV

      - name: Verify Cinc checksum
        run: |
          if ( "${{ env.DOWNLOADED_MSI }}" -eq "${{ env.CINC_CLIENT_SHA256 }}")
          {
              Write-Host "SHA256 checksum matches."
          }
          else
          {
              Write-Warning "SHA256 checksum failure."
              exit 1
          }

      - name: Install Cinc
        run: |
          msiexec /qn /i c:\cinc.msi

      - name: Retrieve data bag key from Github secrets and run Cinc
        working-directory: chef-repo
        run: |
          while (!(Test-Path "C:\cinc-project\cinc\LICENSE")) { Start-Sleep 5 }
          C:\cinc-project\cinc\bin\cinc-client.bat -z -o example
